### ISSUE TITLE
REG_CMD_READ not equal to REG_CMD_WRITE

### ISSUE THREAD

**Issue by grailler** [MatrixOrbital/Eve-School#2]
Hi there!

Using your code I am having a bug where after a while where my REG_CMD_WRITE = 1564 and REG_CMD_READ = 1480. Everything was fine at the previous display list cycle, both registers were always equal.
To give you the context I am displaying some custom fonts + imported images. 
The 4k FIFO rollovers once and then I get stuck forever in the usual while loop waiting for both registers to be equal before entering a new display list.
I also verified that the FIFO entries I write are always 4 bytes wide. Also when I look at the 'free space' in my FIFO, it always returns the nominal 4092, until both registers aren't equal.

Not sure what is going on, any tip ?

**Comment by TharnLago** [comment]
Yeah, I see that all the time and I am still frustrated by it.  I am pretty sure that it is related to Eve being in an error state of some kind.  
I am reduced to power cycling it, but there is a note in the BT documentation about a repair sequence which I ham-handedly tried to implement but failed.  I have been intending to put some time into making it actually work, but it is really difficult to reproduce at will (mostly since I don't know precisely how it happens in the first place).
If you have a way to make it happen, I am willing to spend some time experimenting with the repair sequence.
See the section 5.8 Coprocessor Faults for details.
You might try to retrieve the error message about Eve's problem via the error message pass-through code in the middle of my function Wait4CoProFIFOEmpty().  If the problem is a legitimate error, then knowing what Eve thinks that error is might point you to where to fix it.
The code following that attempts to make the FIFO repair but the code doesn't work and is probably really dumb.
Let me know what you find out.
On Wed, Jun 17, 2020 at 12:08, grailler  wrote:
 Hi there!
 Using your code I am having a bug where after a while where my REG_CMD_WRITE = 1564 and REG_CMD_READ = 1480. Everything was fine at the previous display list cycle, both registers were always equal.
 To give you the context I am displaying some custom fonts + imported images.
 The 4k FIFO rollovers once and then I get stuck forever in the usual while loop waiting for both registers to be equal before entering a new display list.
 I also verified that the FIFO entries I write are always 4 bytes wide. Also when I look at the 'free space' in my FIFO, it always returns the nominal 4092, until both registers aren't equal.
 Not sure what is going on, any tip ?

**Comment by grailler** [comment]
Hi Tharn!
Thanks for the prompt answer. Well problem solved! So the issue is a memory leak on our side, yep..
I noticed the register mismatch each time I display stuff; so when I use the Cmd_Text() function. Then I noticed that the calloc uint32_t* data variable (in the Cmd_Text function) was stored at I different location each time and the address was increasing. Eventually I ran out of heap and the uint32_t* data wasn't stored anywhere. This resulted that I was sending junk to the FT81, which caused a mismatch to the chip's read and write registers.
The root of the memory leakage was that I was not freeing the string I was constructing and passing to the Cmd_Text() function. An easy fix is to free that string after the execution of yout Cmd_Text() function or what I did is use a static array, that way.. no more memory leakage issue! 
I am sure you are having the same issue. If you want to reconstruct this bug, just decrease you heap size and try to only use Cmd_Text() (or even Cmd_Button() actually).

Let me know if that works for you!

**Comment by TharnLago** [comment]
I'll have a look later. Now that you mention it, though, I remember that. It was just a momentary whim that I forgot to take seriously. 

Thank you very much and sorry for the carelessness.
On Wed, Jun 17, 2020 at 15:48, grailler  wrote:
	Hi Tharn!
 Thanks for the prompt answer. Well problem solved! So the issue is a memory leak on our side, yep..
 I noticed the register mismatch each time I display stuff; so when I use the Cmd_Text() function. Then I noticed that the calloc uint32_t* data variable (in the Cmd_Text function) was stored at I different location each time and the address was increasing. Eventually I ran out of heap and the uint32_t* data wasn't stored anywhere. This resulted that I was sending junk to the FT81, which caused a mismatch to the chip's read and write registers.
 The root of the memory leakage was that I was not freeing the string I was constructing and passing to the Cmd_Text() function. An easy fix is to free that string after the execution of yout Cmd_Text() function or what I did is use a static array, that way.. no more memory leakage issue!
 I am sure you are having the same issue. If you want to reconstruct this bug, just decrease you heap size and try to only use Cmd_Text() (or even Cmd_Button() actually). 

	Let me know if that works for you!

**Comment by TharnLago** [comment]
I had a look at it and I guess my assumption of guilt was misplaced.  Tell me if I'm wrong, but I think that those calloc() / free() are ok.  I understand now that your issue was about your own free().

I have updated the library repo with new versions of the pertinent files.  Maybe load those into your project.  The only notable change is a (hopeful) fix to the error recovery code - it was previously impossible to recover successfully.

In my current project, I am experiencing constant CoPro errors, but the process now seems to continue without baggage.  

If you want to talk more comfortably about Eve stuff, join me at 
https://www.lcdforums.com/forums/index.php
